#!/bin/sh

TOP=$(git rev-parse --show-toplevel);

find {$TOP/assets/css,$TOP/assets/js} -name '*.min.*' -exec git rm -rf {} \;;

php $TOP/util/minifyAssets.php;

find {$TOP/assets/css,$TOP/assets/js} -name '*.min.*' -exec git add {} \;;

exit 0;